with parts as (
  -- 0: enum types (before tables that use them)
  select 0 as ord, t.typname as nm,
    'CREATE TYPE public.' || quote_ident(t.typname) || ' AS ENUM (' ||
    string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) || ');' as ddl
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace and n.nspname = 'public'
  group by t.typname

  union all
  -- 1: tables
  select 1, c.relname,
    'CREATE TABLE IF NOT EXISTS public.' || quote_ident(c.relname) || E' (\n  ' ||
    string_agg(
      quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod) ||
      case a.attidentity
        when 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
        when 'a' then ' GENERATED ALWAYS AS IDENTITY'
        else case when ad.adbin is not null then ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end
      end ||
      case when a.attnotnull then ' NOT NULL' else '' end,
      E',\n  ' order by a.attnum) || E'\n);'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
  where c.relkind = 'r'
  group by c.relname

  union all
  -- 2: PK / UNIQUE / CHECK constraints (must precede FKs)
  select 2, rel.relname,
    'ALTER TABLE public.' || quote_ident(rel.relname) || ' ADD CONSTRAINT ' ||
    quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace and n.nspname = 'public'
  where con.contype in ('p', 'u', 'c')

  union all
  -- 3: FOREIGN KEY constraints (after all PK/unique exist)
  select 3, rel.relname,
    'ALTER TABLE public.' || quote_ident(rel.relname) || ' ADD CONSTRAINT ' ||
    quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace and n.nspname = 'public'
  where con.contype = 'f'

  union all
  -- 4: indexes not already backing a constraint
  select 4, i.tablename, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (
      select 1 from pg_constraint c2
      join pg_class ic on ic.oid = c2.conindid
      where ic.relname = i.indexname
    )

  union all
  -- 5: functions
  select 5, p.proname, pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace and n.nspname = 'public'
  where p.prokind = 'f'

  union all
  -- 6: triggers (non-internal)
  select 6, rel.relname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t
  join pg_class rel on rel.oid = t.tgrelid
  join pg_namespace n on n.oid = rel.relnamespace and n.nspname = 'public'
  where not t.tgisinternal

  union all
  -- 7: enable RLS where prod has it on
  select 7, c.relname,
    'ALTER TABLE public.' || quote_ident(c.relname) || ' ENABLE ROW LEVEL SECURITY;'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
  where c.relkind = 'r' and c.relrowsecurity

  union all
  -- 8: policies
  select 8, rel.relname,
    'CREATE POLICY ' || quote_ident(pol.polname) || ' ON public.' || quote_ident(rel.relname) ||
    ' AS ' || case when pol.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end ||
    ' FOR ' || case pol.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' else 'ALL' end ||
    ' TO ' || coalesce((select string_agg(rolname, ', ') from pg_roles where oid = any(pol.polroles)), 'public') ||
    coalesce(' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '') ||
    coalesce(' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '') || ';'
  from pg_policy pol
  join pg_class rel on rel.oid = pol.polrelid
  join pg_namespace n on n.oid = rel.relnamespace and n.nspname = 'public'
)
select string_agg(ddl, E'\n\n' order by ord, nm) as schema_sql from parts;
