-- 0002: Stage A — native pricing + customers (CL-SPEC-001). Additive + re-runnable.
-- Apply to dev:  bash supabase/dev-setup/dev-sql.sh -f supabase/migrations/0002_standalone_pricing_customers.sql
-- Apply to prod (at promotion, gated):  supabase db query --linked -f <this file>  (linked to prod)

-- ── Price book ────────────────────────────────────────────────────────────────
create table if not exists public.price_lists (
  id uuid primary key default gen_random_uuid(),
  franchise_id uuid not null,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- at most one default price list per franchise
create unique index if not exists price_lists_one_default_per_franchise
  on public.price_lists (franchise_id) where is_default;

create table if not exists public.price_blocks (
  id uuid primary key default gen_random_uuid(),
  price_list_id uuid not null references public.price_lists(id) on delete cascade,
  name text not null,
  block_type text not null,                 -- 'volume' | 'surcharge' | 'labor' | 'single_item'
  sequence int not null default 0
);
create index if not exists price_blocks_list_idx on public.price_blocks (price_list_id);

create table if not exists public.price_items (
  id uuid primary key default gen_random_uuid(),
  price_block_id uuid not null references public.price_blocks(id) on delete cascade,
  name text not null,
  value numeric not null,
  unit_of_measure text,                     -- drives frontend decimal behavior
  fraction_value numeric,                   -- 0.25/0.5/… for volume tiers; null otherwise
  sequence int not null default 0,
  is_active boolean not null default true
);
create index if not exists price_items_block_idx on public.price_items (price_block_id);

-- zip → price list (ONE list per zip; unassigned zips fall to the franchise's default list)
create table if not exists public.price_list_zips (
  franchise_id uuid not null,
  zip text not null,
  price_list_id uuid not null references public.price_lists(id) on delete cascade,
  primary key (franchise_id, zip)
);
create index if not exists price_list_zips_list_idx on public.price_list_zips (price_list_id);

-- ── Customers (lean, integration-ready; NOT a CRM) ──────────────────────────────
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  franchise_id uuid not null,
  name text not null,
  type text not null default 'residential', -- 'residential' | 'commercial' (editable)
  address text, zip text, email text, phone text,
  source text not null default 'native',     -- 'native' | 'hubspot' | 'salesforce' | 'vonigo'
  external_id text,                           -- id in the source system (null for native)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists customers_franchise_idx on public.customers (franchise_id);

-- Numeric surrogate IDs for shape-parity with crewlogic-price-lookup (which returns numeric
-- priceListID/priceBlockID/priceItemID; the frontend interpolates some of them unquoted).
alter table public.price_lists  add column if not exists num_id bigint generated by default as identity;
alter table public.price_blocks add column if not exists num_id bigint generated by default as identity;
alter table public.price_items  add column if not exists num_id bigint generated by default as identity;

-- ── RLS ─────────────────────────────────────────────────────────────────────────
-- Permissive policies matching the app's CURRENT pattern (anon via the publishable key,
-- app-level franchise scoping). SEC-1 replaces these with tenant/franchise-scoped policies.
alter table public.price_lists     enable row level security;
alter table public.price_blocks    enable row level security;
alter table public.price_items     enable row level security;
alter table public.price_list_zips enable row level security;
alter table public.customers       enable row level security;

drop policy if exists "stage_a price_lists all"     on public.price_lists;
drop policy if exists "stage_a price_blocks all"    on public.price_blocks;
drop policy if exists "stage_a price_items all"     on public.price_items;
drop policy if exists "stage_a price_list_zips all" on public.price_list_zips;
drop policy if exists "stage_a customers all"       on public.customers;

create policy "stage_a price_lists all"     on public.price_lists     for all to anon, authenticated using (true) with check (true);
create policy "stage_a price_blocks all"    on public.price_blocks    for all to anon, authenticated using (true) with check (true);
create policy "stage_a price_items all"     on public.price_items     for all to anon, authenticated using (true) with check (true);
create policy "stage_a price_list_zips all" on public.price_list_zips for all to anon, authenticated using (true) with check (true);
create policy "stage_a customers all"       on public.customers       for all to anon, authenticated using (true) with check (true);
